#include "data.h"
using namespace std;
vector<Team> createTeams()
{
    vector<Team> quickMatchTeams;
    // ==================== BARCELONA (2011) ====================

    Player bar1;
    bar1.name = "VICTOR VALDES";
    bar1.nationality = "Spanish";
    bar1.role = "Goalkeeper";
    bar1.position = "GK";
    bar1.age = 29;
    bar1.shooting = 8;
    bar1.passing = 50;
    bar1.dribbling = 40;
    bar1.pace = 40;
    bar1.defending = 20;
    bar1.physical = 60;
    bar1.goalkeeping = 87;

    Player bar2;
    bar2.name = "CARLES PUYOL";
    bar2.nationality = "Spanish";
    bar2.role = "Defender";
    bar2.position = "CB";
    bar2.age = 33;
    bar2.shooting = 25;
    bar2.passing = 62;
    bar2.dribbling = 48;
    bar2.pace = 55;
    bar2.defending = 88;
    bar2.physical = 84;
    bar2.goalkeeping = 5;

    Player bar3;
    bar3.name = "GERARD PIQUE";
    bar3.nationality = "Spanish";
    bar3.role = "Defender";
    bar3.position = "CB";
    bar3.age = 24;
    bar3.shooting = 30;
    bar3.passing = 67;
    bar3.dribbling = 55;
    bar3.pace = 58;
    bar3.defending = 87;
    bar3.physical = 78;
    bar3.goalkeeping = 5;

    Player bar4;
    bar4.name = "DANI ALVES";
    bar4.nationality = "Brazilian";
    bar4.role = "Defender";
    bar4.position = "RB";
    bar4.age = 28;
    bar4.shooting = 72;
    bar4.passing = 80;
    bar4.dribbling = 82;
    bar4.pace = 84;
    bar4.defending = 75;
    bar4.physical = 76;
    bar4.goalkeeping = 5;

    Player bar5;
    bar5.name = "XAVI HERNANDEZ";
    bar5.nationality = "Spanish";
    bar5.role = "Midfielder";
    bar5.position = "CM";
    bar5.age = 31;
    bar5.shooting = 70;
    bar5.passing = 98;
    bar5.dribbling = 90;
    bar5.pace = 74;
    bar5.defending = 72;
    bar5.physical = 68;
    bar5.goalkeeping = 5;

    Player bar6;
    bar6.name = "ANDRES INIESTA";
    bar6.nationality = "Spanish";
    bar6.role = "Midfielder";
    bar6.position = "CAM";
    bar6.age = 27;
    bar6.shooting = 74;
    bar6.passing = 92;
    bar6.dribbling = 95;
    bar6.pace = 78;
    bar6.defending = 65;
    bar6.physical = 66;
    bar6.goalkeeping = 5;

    Player bar7;
    bar7.name = "SERGIO BUSQUETS";
    bar7.nationality = "Spanish";
    bar7.role = "Midfielder";
    bar7.position = "CDM";
    bar7.age = 22;
    bar7.shooting = 45;
    bar7.passing = 84;
    bar7.dribbling = 70;
    bar7.pace = 52;
    bar7.defending = 80;
    bar7.physical = 68;
    bar7.goalkeeping = 5;

    Player bar8;
    bar8.name = "CESC FABREGAS";
    bar8.nationality = "Spanish";
    bar8.role = "Midfielder";
    bar8.position = "CM";
    bar8.age = 24;
    bar8.shooting = 74;
    bar8.passing = 90;
    bar8.dribbling = 82;
    bar8.pace = 72;
    bar8.defending = 58;
    bar8.physical = 66;
    bar8.goalkeeping = 5;

    Player bar9;
    bar9.name = "LIONEL MESSI";
    bar9.nationality = "Argentine";
    bar9.role = "Attacker";
    bar9.position = "RW";
    bar9.age = 23;
    bar9.shooting = 96;
    bar9.passing = 90;
    bar9.dribbling = 99;
    bar9.pace = 96;
    bar9.defending = 38;
    bar9.physical = 65;
    bar9.goalkeeping = 5;

    Player bar10;
    bar10.name = "DAVID VILLA";
    bar10.nationality = "Spanish";
    bar10.role = "Attacker";
    bar10.position = "ST";
    bar10.age = 29;
    bar10.shooting = 90;
    bar10.passing = 74;
    bar10.dribbling = 78;
    bar10.pace = 82;
    bar10.defending = 35;
    bar10.physical = 72;
    bar10.goalkeeping = 5;

    Player bar11;
    bar11.name = "PEDRO RODRIGUEZ";
    bar11.nationality = "Spanish";
    bar11.role = "Attacker";
    bar11.position = "LW";
    bar11.age = 23;
    bar11.shooting = 80;
    bar11.passing = 72;
    bar11.dribbling = 78;
    bar11.pace = 86;
    bar11.defending = 38;
    bar11.physical = 66;
    bar11.goalkeeping = 5;

    Team bar;
    bar.name = "BARCELONA";
    bar.players.push_back(bar1);
    bar.players.push_back(bar2);
    bar.players.push_back(bar3);
    bar.players.push_back(bar4);
    bar.players.push_back(bar5);
    bar.players.push_back(bar6);
    bar.players.push_back(bar7);
    bar.players.push_back(bar8);
    bar.players.push_back(bar9);
    bar.players.push_back(bar10);
    bar.players.push_back(bar11);

    // ==================== REAL MADRID (2017) ====================

    Player rma1;
    rma1.name = "KEYLOR NAVAS";
    rma1.nationality = "Costa Rican";
    rma1.role = "Goalkeeper";
    rma1.position = "GK";
    rma1.age = 30;
    rma1.shooting = 10;
    rma1.passing = 52;
    rma1.dribbling = 42;
    rma1.pace = 44;
    rma1.defending = 22;
    rma1.physical = 58;
    rma1.goalkeeping = 87;

    Player rma2;
    rma2.name = "SERGIO RAMOS";
    rma2.nationality = "Spanish";
    rma2.role = "Defender";
    rma2.position = "CB";
    rma2.age = 31;
    rma2.shooting = 62;
    rma2.passing = 72;
    rma2.dribbling = 66;
    rma2.pace = 60;
    rma2.defending = 91;
    rma2.physical = 84;
    rma2.goalkeeping = 5;

    Player rma3;
    rma3.name = "RAPHAEL VARANE";
    rma3.nationality = "French";
    rma3.role = "Defender";
    rma3.position = "CB";
    rma3.age = 24;
    rma3.shooting = 28;
    rma3.passing = 64;
    rma3.dribbling = 60;
    rma3.pace = 74;
    rma3.defending = 87;
    rma3.physical = 76;
    rma3.goalkeeping = 5;

    Player rma4;
    rma4.name = "DANI CARVAJAL";
    rma4.nationality = "Spanish";
    rma4.role = "Defender";
    rma4.position = "RB";
    rma4.age = 25;
    rma4.shooting = 55;
    rma4.passing = 72;
    rma4.dribbling = 72;
    rma4.pace = 80;
    rma4.defending = 76;
    rma4.physical = 72;
    rma4.goalkeeping = 5;

    Player rma5;
    rma5.name = "MARCELO";
    rma5.nationality = "Brazilian";
    rma5.role = "Defender";
    rma5.position = "LB";
    rma5.age = 29;
    rma5.shooting = 62;
    rma5.passing = 80;
    rma5.dribbling = 84;
    rma5.pace = 82;
    rma5.defending = 66;
    rma5.physical = 72;
    rma5.goalkeeping = 5;

    Player rma6;
    rma6.name = "LUKA MODRIC";
    rma6.nationality = "Croatian";
    rma6.role = "Midfielder";
    rma6.position = "CM";
    rma6.age = 31;
    rma6.shooting = 72;
    rma6.passing = 92;
    rma6.dribbling = 90;
    rma6.pace = 78;
    rma6.defending = 72;
    rma6.physical = 68;
    rma6.goalkeeping = 5;

    Player rma7;
    rma7.name = "TONI KROOS";
    rma7.nationality = "German";
    rma7.role = "Midfielder";
    rma7.position = "CM";
    rma7.age = 27;
    rma7.shooting = 78;
    rma7.passing = 95;
    rma7.dribbling = 78;
    rma7.pace = 58;
    rma7.defending = 72;
    rma7.physical = 72;
    rma7.goalkeeping = 5;

    Player rma8;
    rma8.name = "CASEMIRO";
    rma8.nationality = "Brazilian";
    rma8.role = "Midfielder";
    rma8.position = "CDM";
    rma8.age = 25;
    rma8.shooting = 52;
    rma8.passing = 72;
    rma8.dribbling = 62;
    rma8.pace = 56;
    rma8.defending = 88;
    rma8.physical = 84;
    rma8.goalkeeping = 5;

    Player rma9;
    rma9.name = "CRISTIANO RONALDO";
    rma9.nationality = "Portuguese";
    rma9.role = "Attacker";
    rma9.position = "ST";
    rma9.age = 32;
    rma9.shooting = 98;
    rma9.passing = 78;
    rma9.dribbling = 88;
    rma9.pace = 90;
    rma9.defending = 38;
    rma9.physical = 88;
    rma9.goalkeeping = 5;

    Player rma10;
    rma10.name = "KARIM BENZEMA";
    rma10.nationality = "French";
    rma10.role = "Attacker";
    rma10.position = "CF";
    rma10.age = 29;
    rma10.shooting = 88;
    rma10.passing = 82;
    rma10.dribbling = 82;
    rma10.pace = 76;
    rma10.defending = 40;
    rma10.physical = 78;
    rma10.goalkeeping = 5;

    Player rma11;
    rma11.name = "GARETH BALE";
    rma11.nationality = "Welsh";
    rma11.role = "Attacker";
    rma11.position = "LW";
    rma11.age = 27;
    rma11.shooting = 88;
    rma11.passing = 72;
    rma11.dribbling = 82;
    rma11.pace = 95;
    rma11.defending = 36;
    rma11.physical = 78;
    rma11.goalkeeping = 5;

    Team rma;
    rma.name = "REAL MADRID";
    rma.players.push_back(rma1);
    rma.players.push_back(rma2);
    rma.players.push_back(rma3);
    rma.players.push_back(rma4);
    rma.players.push_back(rma5);
    rma.players.push_back(rma6);
    rma.players.push_back(rma7);
    rma.players.push_back(rma8);
    rma.players.push_back(rma9);
    rma.players.push_back(rma10);
    rma.players.push_back(rma11);

    // ==================== MANCHESTER UNITED (2008) ====================

    Player mnu1;
    mnu1.name = "EDWIN VAN DER SAR";
    mnu1.nationality = "Dutch";
    mnu1.role = "Goalkeeper";
    mnu1.position = "GK";
    mnu1.age = 37;
    mnu1.shooting = 10;
    mnu1.passing = 50;
    mnu1.dribbling = 38;
    mnu1.pace = 35;
    mnu1.defending = 20;
    mnu1.physical = 62;
    mnu1.goalkeeping = 89;

    Player mnu2;
    mnu2.name = "RIO FERDINAND";
    mnu2.nationality = "English";
    mnu2.role = "Defender";
    mnu2.position = "CB";
    mnu2.age = 29;
    mnu2.shooting = 30;
    mnu2.passing = 65;
    mnu2.dribbling = 56;
    mnu2.pace = 64;
    mnu2.defending = 89;
    mnu2.physical = 76;
    mnu2.goalkeeping = 5;

    Player mnu3;
    mnu3.name = "NEMANJA VIDIC";
    mnu3.nationality = "Serbian";
    mnu3.role = "Defender";
    mnu3.position = "CB";
    mnu3.age = 26;
    mnu3.shooting = 28;
    mnu3.passing = 52;
    mnu3.dribbling = 44;
    mnu3.pace = 56;
    mnu3.defending = 92;
    mnu3.physical = 88;
    mnu3.goalkeeping = 5;

    Player mnu4;
    mnu4.name = "PATRICE EVRA";
    mnu4.nationality = "French";
    mnu4.role = "Defender";
    mnu4.position = "LB";
    mnu4.age = 27;
    mnu4.shooting = 45;
    mnu4.passing = 68;
    mnu4.dribbling = 66;
    mnu4.pace = 76;
    mnu4.defending = 78;
    mnu4.physical = 72;
    mnu4.goalkeeping = 5;

    Player mnu5;
    mnu5.name = "PAUL SCHOLES";
    mnu5.nationality = "English";
    mnu5.role = "Midfielder";
    mnu5.position = "CM";
    mnu5.age = 33;
    mnu5.shooting = 82;
    mnu5.passing = 88;
    mnu5.dribbling = 76;
    mnu5.pace = 52;
    mnu5.defending = 68;
    mnu5.physical = 68;
    mnu5.goalkeeping = 5;

    Player mnu6;
    mnu6.name = "RYAN GIGGS";
    mnu6.nationality = "Welsh";
    mnu6.role = "Midfielder";
    mnu6.position = "LM";
    mnu6.age = 34;
    mnu6.shooting = 72;
    mnu6.passing = 82;
    mnu6.dribbling = 84;
    mnu6.pace = 76;
    mnu6.defending = 58;
    mnu6.physical = 66;
    mnu6.goalkeeping = 5;

    Player mnu7;
    mnu7.name = "MICHAEL CARRICK";
    mnu7.nationality = "English";
    mnu7.role = "Midfielder";
    mnu7.position = "CDM";
    mnu7.age = 26;
    mnu7.shooting = 52;
    mnu7.passing = 82;
    mnu7.dribbling = 66;
    mnu7.pace = 54;
    mnu7.defending = 76;
    mnu7.physical = 68;
    mnu7.goalkeeping = 5;

    Player mnu8;
    mnu8.name = "OWEN HARGREAVES";
    mnu8.nationality = "English";
    mnu8.role = "Midfielder";
    mnu8.position = "CDM";
    mnu8.age = 27;
    mnu8.shooting = 50;
    mnu8.passing = 72;
    mnu8.dribbling = 62;
    mnu8.pace = 72;
    mnu8.defending = 78;
    mnu8.physical = 74;
    mnu8.goalkeeping = 5;

    Player mnu9;
    mnu9.name = "CRISTIANO RONALDO";
    mnu9.nationality = "Portuguese";
    mnu9.role = "Attacker";
    mnu9.position = "RW";
    mnu9.age = 23;
    mnu9.shooting = 90;
    mnu9.passing = 76;
    mnu9.dribbling = 94;
    mnu9.pace = 96;
    mnu9.defending = 36;
    mnu9.physical = 78;
    mnu9.goalkeeping = 5;

    Player mnu10;
    mnu10.name = "WAYNE ROONEY";
    mnu10.nationality = "English";
    mnu10.role = "Attacker";
    mnu10.position = "ST";
    mnu10.age = 22;
    mnu10.shooting = 88;
    mnu10.passing = 78;
    mnu10.dribbling = 82;
    mnu10.pace = 78;
    mnu10.defending = 44;
    mnu10.physical = 82;
    mnu10.goalkeeping = 5;

    Player mnu11;
    mnu11.name = "CARLOS TEVEZ";
    mnu11.nationality = "Argentine";
    mnu11.role = "Attacker";
    mnu11.position = "CF";
    mnu11.age = 24;
    mnu11.shooting = 82;
    mnu11.passing = 70;
    mnu11.dribbling = 84;
    mnu11.pace = 82;
    mnu11.defending = 40;
    mnu11.physical = 80;
    mnu11.goalkeeping = 5;

    Team mnu;
    mnu.name = "MANCHESTER UNITED";
    mnu.players.push_back(mnu1);
    mnu.players.push_back(mnu2);
    mnu.players.push_back(mnu3);
    mnu.players.push_back(mnu4);
    mnu.players.push_back(mnu5);
    mnu.players.push_back(mnu6);
    mnu.players.push_back(mnu7);
    mnu.players.push_back(mnu8);
    mnu.players.push_back(mnu9);
    mnu.players.push_back(mnu10);
    mnu.players.push_back(mnu11);

    // ==================== CHELSEA (2005) ====================

    Player che1;
    che1.name = "PETR CECH";
    che1.nationality = "Czech";
    che1.role = "Goalkeeper";
    che1.position = "GK";
    che1.age = 23;
    che1.shooting = 10;
    che1.passing = 50;
    che1.dribbling = 38;
    che1.pace = 40;
    che1.defending = 22;
    che1.physical = 64;
    che1.goalkeeping = 91;

    Player che2;
    che2.name = "JOHN TERRY";
    che2.nationality = "English";
    che2.role = "Defender";
    che2.position = "CB";
    che2.age = 24;
    che2.shooting = 38;
    che2.passing = 62;
    che2.dribbling = 50;
    che2.pace = 54;
    che2.defending = 92;
    che2.physical = 88;
    che2.goalkeeping = 5;

    Player che3;
    che3.name = "RICARDO CARVALHO";
    che3.nationality = "Portuguese";
    che3.role = "Defender";
    che3.position = "CB";
    che3.age = 27;
    che3.shooting = 28;
    che3.passing = 58;
    che3.dribbling = 50;
    che3.pace = 56;
    che3.defending = 89;
    che3.physical = 80;
    che3.goalkeeping = 5;

    Player che4;
    che4.name = "WILLIAM GALLAS";
    che4.nationality = "French";
    che4.role = "Defender";
    che4.position = "CB";
    che4.age = 27;
    che4.shooting = 35;
    che4.passing = 60;
    che4.dribbling = 60;
    che4.pace = 72;
    che4.defending = 82;
    che4.physical = 76;
    che4.goalkeeping = 5;

    Player che5;
    che5.name = "FRANK LAMPARD";
    che5.nationality = "English";
    che5.role = "Midfielder";
    che5.position = "CM";
    che5.age = 26;
    che5.shooting = 88;
    che5.passing = 84;
    che5.dribbling = 74;
    che5.pace = 66;
    che5.defending = 68;
    che5.physical = 82;
    che5.goalkeeping = 5;

    Player che6;
    che6.name = "CLAUDE MAKELELE";
    che6.nationality = "French";
    che6.role = "Midfielder";
    che6.position = "CDM";
    che6.age = 32;
    che6.shooting = 42;
    che6.passing = 72;
    che6.dribbling = 64;
    che6.pace = 56;
    che6.defending = 84;
    che6.physical = 76;
    che6.goalkeeping = 5;

    Player che7;
    che7.name = "MICHAEL ESSIEN";
    che7.nationality = "Ghanaian";
    che7.role = "Midfielder";
    che7.position = "CM";
    che7.age = 22;
    che7.shooting = 68;
    che7.passing = 72;
    che7.dribbling = 72;
    che7.pace = 78;
    che7.defending = 78;
    che7.physical = 86;
    che7.goalkeeping = 5;

    Player che8;
    che8.name = "JOE COLE";
    che8.nationality = "English";
    che8.role = "Midfielder";
    che8.position = "LM";
    che8.age = 23;
    che8.shooting = 72;
    che8.passing = 74;
    che8.dribbling = 80;
    che8.pace = 78;
    che8.defending = 44;
    che8.physical = 64;
    che8.goalkeeping = 5;

    Player che9;
    che9.name = "DIDIER DROGBA";
    che9.nationality = "Ivorian";
    che9.role = "Attacker";
    che9.position = "ST";
    che9.age = 27;
    che9.shooting = 88;
    che9.passing = 68;
    che9.dribbling = 72;
    che9.pace = 76;
    che9.defending = 38;
    che9.physical = 90;
    che9.goalkeeping = 5;

    Player che10;
    che10.name = "ARJEN ROBBEN";
    che10.nationality = "Dutch";
    che10.role = "Attacker";
    che10.position = "RW";
    che10.age = 21;
    che10.shooting = 80;
    che10.passing = 74;
    che10.dribbling = 88;
    che10.pace = 88;
    che10.defending = 34;
    che10.physical = 66;
    che10.goalkeeping = 5;

    Player che11;
    che11.name = "DAMIEN DUFF";
    che11.nationality = "Irish";
    che11.role = "Attacker";
    che11.position = "LW";
    che11.age = 26;
    che11.shooting = 72;
    che11.passing = 72;
    che11.dribbling = 82;
    che11.pace = 86;
    che11.defending = 36;
    che11.physical = 64;
    che11.goalkeeping = 5;

    Team che;
    che.name = "CHELSEA";
    che.players.push_back(che1);
    che.players.push_back(che2);
    che.players.push_back(che3);
    che.players.push_back(che4);
    che.players.push_back(che5);
    che.players.push_back(che6);
    che.players.push_back(che7);
    che.players.push_back(che8);
    che.players.push_back(che9);
    che.players.push_back(che10);
    che.players.push_back(che11);

    // ==================== LIVERPOOL (2020) ====================

    Player liv1;
    liv1.name = "ALISSON BECKER";
    liv1.nationality = "Brazilian";
    liv1.role = "Goalkeeper";
    liv1.position = "GK";
    liv1.age = 27;
    liv1.shooting = 10;
    liv1.passing = 58;
    liv1.dribbling = 40;
    liv1.pace = 42;
    liv1.defending = 24;
    liv1.physical = 62;
    liv1.goalkeeping = 92;

    Player liv2;
    liv2.name = "VIRGIL VAN DIJK";
    liv2.nationality = "Dutch";
    liv2.role = "Defender";
    liv2.position = "CB";
    liv2.age = 28;
    liv2.shooting = 42;
    liv2.passing = 70;
    liv2.dribbling = 58;
    liv2.pace = 72;
    liv2.defending = 93;
    liv2.physical = 88;
    liv2.goalkeeping = 5;

    Player liv3;
    liv3.name = "JOEL MATIP";
    liv3.nationality = "Cameroonian";
    liv3.role = "Defender";
    liv3.position = "CB";
    liv3.age = 28;
    liv3.shooting = 28;
    liv3.passing = 60;
    liv3.dribbling = 52;
    liv3.pace = 64;
    liv3.defending = 84;
    liv3.physical = 80;
    liv3.goalkeeping = 5;

    Player liv4;
    liv4.name = "TRENT ALEXANDER-ARNOLD";
    liv4.nationality = "English";
    liv4.role = "Defender";
    liv4.position = "RB";
    liv4.age = 21;
    liv4.shooting = 72;
    liv4.passing = 88;
    liv4.dribbling = 72;
    liv4.pace = 80;
    liv4.defending = 66;
    liv4.physical = 68;
    liv4.goalkeeping = 5;

    Player liv5;
    liv5.name = "ANDREW ROBERTSON";
    liv5.nationality = "Scottish";
    liv5.role = "Defender";
    liv5.position = "LB";
    liv5.age = 26;
    liv5.shooting = 62;
    liv5.passing = 80;
    liv5.dribbling = 74;
    liv5.pace = 84;
    liv5.defending = 74;
    liv5.physical = 76;
    liv5.goalkeeping = 5;

    Player liv6;
    liv6.name = "JORDAN HENDERSON";
    liv6.nationality = "English";
    liv6.role = "Midfielder";
    liv6.position = "CM";
    liv6.age = 29;
    liv6.shooting = 62;
    liv6.passing = 78;
    liv6.dribbling = 68;
    liv6.pace = 70;
    liv6.defending = 76;
    liv6.physical = 80;
    liv6.goalkeeping = 5;

    Player liv7;
    liv7.name = "FABINHO";
    liv7.nationality = "Brazilian";
    liv7.role = "Midfielder";
    liv7.position = "CDM";
    liv7.age = 26;
    liv7.shooting = 52;
    liv7.passing = 74;
    liv7.dribbling = 68;
    liv7.pace = 60;
    liv7.defending = 86;
    liv7.physical = 80;
    liv7.goalkeeping = 5;

    Player liv8;
    liv8.name = "GEORGINIO WIJNALDUM";
    liv8.nationality = "Dutch";
    liv8.role = "Midfielder";
    liv8.position = "CM";
    liv8.age = 29;
    liv8.shooting = 68;
    liv8.passing = 78;
    liv8.dribbling = 76;
    liv8.pace = 72;
    liv8.defending = 66;
    liv8.physical = 78;
    liv8.goalkeeping = 5;

    Player liv9;
    liv9.name = "MOHAMED SALAH";
    liv9.nationality = "Egyptian";
    liv9.role = "Attacker";
    liv9.position = "RW";
    liv9.age = 27;
    liv9.shooting = 90;
    liv9.passing = 76;
    liv9.dribbling = 90;
    liv9.pace = 92;
    liv9.defending = 38;
    liv9.physical = 72;
    liv9.goalkeeping = 5;

    Player liv10;
    liv10.name = "SADIO MANE";
    liv10.nationality = "Senegalese";
    liv10.role = "Attacker";
    liv10.position = "LW";
    liv10.age = 28;
    liv10.shooting = 88;
    liv10.passing = 74;
    liv10.dribbling = 88;
    liv10.pace = 90;
    liv10.defending = 40;
    liv10.physical = 76;
    liv10.goalkeeping = 5;

    Player liv11;
    liv11.name = "ROBERTO FIRMINO";
    liv11.nationality = "Brazilian";
    liv11.role = "Attacker";
    liv11.position = "CF";
    liv11.age = 28;
    liv11.shooting = 80;
    liv11.passing = 82;
    liv11.dribbling = 84;
    liv11.pace = 72;
    liv11.defending = 52;
    liv11.physical = 72;
    liv11.goalkeeping = 5;

    Team liv;
    liv.name = "LIVERPOOL";
    liv.players.push_back(liv1);
    liv.players.push_back(liv2);
    liv.players.push_back(liv3);
    liv.players.push_back(liv4);
    liv.players.push_back(liv5);
    liv.players.push_back(liv6);
    liv.players.push_back(liv7);
    liv.players.push_back(liv8);
    liv.players.push_back(liv9);
    liv.players.push_back(liv10);
    liv.players.push_back(liv11);

    // ==================== MANCHESTER CITY (2023) ====================

    Player mci1;
    mci1.name = "EDERSON";
    mci1.nationality = "Brazilian";
    mci1.role = "Goalkeeper";
    mci1.position = "GK";
    mci1.age = 29;
    mci1.shooting = 35;
    mci1.passing = 78;
    mci1.dribbling = 50;
    mci1.pace = 48;
    mci1.defending = 20;
    mci1.physical = 66;
    mci1.goalkeeping = 91;

    Player mci2;
    mci2.name = "RUBEN DIAS";
    mci2.nationality = "Portuguese";
    mci2.role = "Defender";
    mci2.position = "CB";
    mci2.age = 25;
    mci2.shooting = 30;
    mci2.passing = 66;
    mci2.dribbling = 52;
    mci2.pace = 62;
    mci2.defending = 91;
    mci2.physical = 84;
    mci2.goalkeeping = 5;

    Player mci3;
    mci3.name = "JOHN STONES";
    mci3.nationality = "English";
    mci3.role = "Defender";
    mci3.position = "CB";
    mci3.age = 28;
    mci3.shooting = 34;
    mci3.passing = 74;
    mci3.dribbling = 60;
    mci3.pace = 60;
    mci3.defending = 86;
    mci3.physical = 76;
    mci3.goalkeeping = 5;

    Player mci4;
    mci4.name = "KYLE WALKER";
    mci4.nationality = "English";
    mci4.role = "Defender";
    mci4.position = "RB";
    mci4.age = 32;
    mci4.shooting = 52;
    mci4.passing = 68;
    mci4.dribbling = 70;
    mci4.pace = 92;
    mci4.defending = 78;
    mci4.physical = 80;
    mci4.goalkeeping = 5;

    Player mci5;
    mci5.name = "KEVIN DE BRUYNE";
    mci5.nationality = "Belgian";
    mci5.role = "Midfielder";
    mci5.position = "CAM";
    mci5.age = 31;
    mci5.shooting = 88;
    mci5.passing = 97;
    mci5.dribbling = 88;
    mci5.pace = 76;
    mci5.defending = 64;
    mci5.physical = 78;
    mci5.goalkeeping = 5;

    Player mci6;
    mci6.name = "RODRI";
    mci6.nationality = "Spanish";
    mci6.role = "Midfielder";
    mci6.position = "CDM";
    mci6.age = 26;
    mci6.shooting = 60;
    mci6.passing = 84;
    mci6.dribbling = 72;
    mci6.pace = 58;
    mci6.defending = 88;
    mci6.physical = 82;
    mci6.goalkeeping = 5;

    Player mci7;
    mci7.name = "BERNARDO SILVA";
    mci7.nationality = "Portuguese";
    mci7.role = "Midfielder";
    mci7.position = "CM";
    mci7.age = 28;
    mci7.shooting = 76;
    mci7.passing = 88;
    mci7.dribbling = 88;
    mci7.pace = 78;
    mci7.defending = 64;
    mci7.physical = 70;
    mci7.goalkeeping = 5;

    Player mci8;
    mci8.name = "ILKAY GUNDOGAN";
    mci8.nationality = "German";
    mci8.role = "Midfielder";
    mci8.position = "CM";
    mci8.age = 32;
    mci8.shooting = 78;
    mci8.passing = 86;
    mci8.dribbling = 78;
    mci8.pace = 62;
    mci8.defending = 66;
    mci8.physical = 70;
    mci8.goalkeeping = 5;

    Player mci9;
    mci9.name = "ERLING HAALAND";
    mci9.nationality = "Norwegian";
    mci9.role = "Attacker";
    mci9.position = "ST";
    mci9.age = 22;
    mci9.shooting = 96;
    mci9.passing = 64;
    mci9.dribbling = 76;
    mci9.pace = 89;
    mci9.defending = 36;
    mci9.physical = 88;
    mci9.goalkeeping = 5;

    Player mci10;
    mci10.name = "JACK GREALISH";
    mci10.nationality = "English";
    mci10.role = "Attacker";
    mci10.position = "LW";
    mci10.age = 27;
    mci10.shooting = 72;
    mci10.passing = 78;
    mci10.dribbling = 86;
    mci10.pace = 74;
    mci10.defending = 42;
    mci10.physical = 68;
    mci10.goalkeeping = 5;

    Player mci11;
    mci11.name = "PHIL FODEN";
    mci11.nationality = "English";
    mci11.role = "Attacker";
    mci11.position = "RW";
    mci11.age = 22;
    mci11.shooting = 82;
    mci11.passing = 84;
    mci11.dribbling = 88;
    mci11.pace = 78;
    mci11.defending = 44;
    mci11.physical = 68;
    mci11.goalkeeping = 5;

    Team mci;
    mci.name = "MANCHESTER CITY";
    mci.players.push_back(mci1);
    mci.players.push_back(mci2);
    mci.players.push_back(mci3);
    mci.players.push_back(mci4);
    mci.players.push_back(mci5);
    mci.players.push_back(mci6);
    mci.players.push_back(mci7);
    mci.players.push_back(mci8);
    mci.players.push_back(mci9);
    mci.players.push_back(mci10);
    mci.players.push_back(mci11);

    // ==================== AC MILAN (2004) ====================

    Player mil1;
    mil1.name = "DIDA";
    mil1.nationality = "Brazilian";
    mil1.role = "Goalkeeper";
    mil1.position = "GK";
    mil1.age = 30;
    mil1.shooting = 10;
    mil1.passing = 48;
    mil1.dribbling = 38;
    mil1.pace = 38;
    mil1.defending = 20;
    mil1.physical = 60;
    mil1.goalkeeping = 88;

    Player mil2;
    mil2.name = "PAOLO MALDINI";
    mil2.nationality = "Italian";
    mil2.role = "Defender";
    mil2.position = "LB";
    mil2.age = 35;
    mil2.shooting = 38;
    mil2.passing = 72;
    mil2.dribbling = 68;
    mil2.pace = 68;
    mil2.defending = 92;
    mil2.physical = 78;
    mil2.goalkeeping = 5;

    Player mil3;
    mil3.name = "ALESSANDRO NESTA";
    mil3.nationality = "Italian";
    mil3.role = "Defender";
    mil3.position = "CB";
    mil3.age = 28;
    mil3.shooting = 28;
    mil3.passing = 62;
    mil3.dribbling = 56;
    mil3.pace = 60;
    mil3.defending = 93;
    mil3.physical = 80;
    mil3.goalkeeping = 5;

    Player mil4;
    mil4.name = "CAFU";
    mil4.nationality = "Brazilian";
    mil4.role = "Defender";
    mil4.position = "RB";
    mil4.age = 33;
    mil4.shooting = 64;
    mil4.passing = 72;
    mil4.dribbling = 76;
    mil4.pace = 84;
    mil4.defending = 76;
    mil4.physical = 76;
    mil4.goalkeeping = 5;

    Player mil5;
    mil5.name = "ANDREA PIRLO";
    mil5.nationality = "Italian";
    mil5.role = "Midfielder";
    mil5.position = "CDM";
    mil5.age = 25;
    mil5.shooting = 72;
    mil5.passing = 94;
    mil5.dribbling = 72;
    mil5.pace = 52;
    mil5.defending = 70;
    mil5.physical = 66;
    mil5.goalkeeping = 5;

    Player mil6;
    mil6.name = "CLARENCE SEEDORF";
    mil6.nationality = "Dutch";
    mil6.role = "Midfielder";
    mil6.position = "CM";
    mil6.age = 28;
    mil6.shooting = 76;
    mil6.passing = 82;
    mil6.dribbling = 78;
    mil6.pace = 70;
    mil6.defending = 68;
    mil6.physical = 76;
    mil6.goalkeeping = 5;

    Player mil7;
    mil7.name = "GENNARO GATTUSO";
    mil7.nationality = "Italian";
    mil7.role = "Midfielder";
    mil7.position = "CDM";
    mil7.age = 26;
    mil7.shooting = 52;
    mil7.passing = 68;
    mil7.dribbling = 62;
    mil7.pace = 72;
    mil7.defending = 82;
    mil7.physical = 88;
    mil7.goalkeeping = 5;

    Player mil8;
    mil8.name = "KAKA";
    mil8.nationality = "Brazilian";
    mil8.role = "Midfielder";
    mil8.position = "CAM";
    mil8.age = 22;
    mil8.shooting = 82;
    mil8.passing = 82;
    mil8.dribbling = 90;
    mil8.pace = 84;
    mil8.defending = 38;
    mil8.physical = 70;
    mil8.goalkeeping = 5;

    Player mil9;
    mil9.name = "ANDRIY SHEVCHENKO";
    mil9.nationality = "Ukrainian";
    mil9.role = "Attacker";
    mil9.position = "ST";
    mil9.age = 27;
    mil9.shooting = 93;
    mil9.passing = 72;
    mil9.dribbling = 82;
    mil9.pace = 88;
    mil9.defending = 36;
    mil9.physical = 76;
    mil9.goalkeeping = 5;

    Player mil10;
    mil10.name = "FILIPPO INZAGHI";
    mil10.nationality = "Italian";
    mil10.role = "Attacker";
    mil10.position = "ST";
    mil10.age = 30;
    mil10.shooting = 88;
    mil10.passing = 58;
    mil10.dribbling = 62;
    mil10.pace = 70;
    mil10.defending = 30;
    mil10.physical = 68;
    mil10.goalkeeping = 5;

    Player mil11;
    mil11.name = "HERNAN CRESPO";
    mil11.nationality = "Argentine";
    mil11.role = "Attacker";
    mil11.position = "CF";
    mil11.age = 28;
    mil11.shooting = 87;
    mil11.passing = 68;
    mil11.dribbling = 72;
    mil11.pace = 72;
    mil11.defending = 30;
    mil11.physical = 72;
    mil11.goalkeeping = 5;

    Team mil;
    mil.name = "AC MILAN";
    mil.players.push_back(mil1);
    mil.players.push_back(mil2);
    mil.players.push_back(mil3);
    mil.players.push_back(mil4);
    mil.players.push_back(mil5);
    mil.players.push_back(mil6);
    mil.players.push_back(mil7);
    mil.players.push_back(mil8);
    mil.players.push_back(mil9);
    mil.players.push_back(mil10);
    mil.players.push_back(mil11);

    // ==================== JUVENTUS (2015) ====================

    Player juv1;
    juv1.name = "GIANLUIGI BUFFON";
    juv1.nationality = "Italian";
    juv1.role = "Goalkeeper";
    juv1.position = "GK";
    juv1.age = 37;
    juv1.shooting = 10;
    juv1.passing = 50;
    juv1.dribbling = 40;
    juv1.pace = 38;
    juv1.defending = 22;
    juv1.physical = 66;
    juv1.goalkeeping = 93;

    Player juv2;
    juv2.name = "GIORGIO CHIELLINI";
    juv2.nationality = "Italian";
    juv2.role = "Defender";
    juv2.position = "CB";
    juv2.age = 30;
    juv2.shooting = 32;
    juv2.passing = 58;
    juv2.dribbling = 52;
    juv2.pace = 58;
    juv2.defending = 91;
    juv2.physical = 86;
    juv2.goalkeeping = 5;

    Player juv3;
    juv3.name = "LEONARDO BONUCCI";
    juv3.nationality = "Italian";
    juv3.role = "Defender";
    juv3.position = "CB";
    juv3.age = 28;
    juv3.shooting = 38;
    juv3.passing = 78;
    juv3.dribbling = 60;
    juv3.pace = 60;
    juv3.defending = 88;
    juv3.physical = 78;
    juv3.goalkeeping = 5;

    Player juv4;
    juv4.name = "ANDREA BARZAGLI";
    juv4.nationality = "Italian";
    juv4.role = "Defender";
    juv4.position = "CB";
    juv4.age = 33;
    juv4.shooting = 24;
    juv4.passing = 58;
    juv4.dribbling = 50;
    juv4.pace = 56;
    juv4.defending = 87;
    juv4.physical = 78;
    juv4.goalkeeping = 5;

    Player juv5;
    juv5.name = "PAUL POGBA";
    juv5.nationality = "French";
    juv5.role = "Midfielder";
    juv5.position = "CM";
    juv5.age = 22;
    juv5.shooting = 78;
    juv5.passing = 82;
    juv5.dribbling = 86;
    juv5.pace = 72;
    juv5.defending = 72;
    juv5.physical = 88;
    juv5.goalkeeping = 5;

    Player juv6;
    juv6.name = "ARTURO VIDAL";
    juv6.nationality = "Chilean";
    juv6.role = "Midfielder";
    juv6.position = "CM";
    juv6.age = 27;
    juv6.shooting = 78;
    juv6.passing = 78;
    juv6.dribbling = 76;
    juv6.pace = 74;
    juv6.defending = 76;
    juv6.physical = 88;
    juv6.goalkeeping = 5;

    Player juv7;
    juv7.name = "CLAUDIO MARCHISIO";
    juv7.nationality = "Italian";
    juv7.role = "Midfielder";
    juv7.position = "CM";
    juv7.age = 29;
    juv7.shooting = 72;
    juv7.passing = 80;
    juv7.dribbling = 74;
    juv7.pace = 70;
    juv7.defending = 72;
    juv7.physical = 76;
    juv7.goalkeeping = 5;

    Player juv8;
    juv8.name = "ANDREA PIRLO";
    juv8.nationality = "Italian";
    juv8.role = "Midfielder";
    juv8.position = "CDM";
    juv8.age = 35;
    juv8.shooting = 64;
    juv8.passing = 92;
    juv8.dribbling = 70;
    juv8.pace = 44;
    juv8.defending = 66;
    juv8.physical = 62;
    juv8.goalkeeping = 5;

    Player juv9;
    juv9.name = "CARLOS TEVEZ";
    juv9.nationality = "Argentine";
    juv9.role = "Attacker";
    juv9.position = "ST";
    juv9.age = 31;
    juv9.shooting = 84;
    juv9.passing = 72;
    juv9.dribbling = 84;
    juv9.pace = 74;
    juv9.defending = 40;
    juv9.physical = 82;
    juv9.goalkeeping = 5;

    Player juv10;
    juv10.name = "ALVARO MORATA";
    juv10.nationality = "Spanish";
    juv10.role = "Attacker";
    juv10.position = "ST";
    juv10.age = 22;
    juv10.shooting = 80;
    juv10.passing = 68;
    juv10.dribbling = 72;
    juv10.pace = 74;
    juv10.defending = 38;
    juv10.physical = 72;
    juv10.goalkeeping = 5;

    Player juv11;
    juv11.name = "PAULO DYBALA";
    juv11.nationality = "Argentine";
    juv11.role = "Attacker";
    juv11.position = "CF";
    juv11.age = 21;
    juv11.shooting = 82;
    juv11.passing = 76;
    juv11.dribbling = 88;
    juv11.pace = 76;
    juv11.defending = 36;
    juv11.physical = 66;
    juv11.goalkeeping = 5;

    Team juv;
    juv.name = "JUVENTUS";
    juv.players.push_back(juv1);
    juv.players.push_back(juv2);
    juv.players.push_back(juv3);
    juv.players.push_back(juv4);
    juv.players.push_back(juv5);
    juv.players.push_back(juv6);
    juv.players.push_back(juv7);
    juv.players.push_back(juv8);
    juv.players.push_back(juv9);
    juv.players.push_back(juv10);
    juv.players.push_back(juv11);

    // ==================== INTER MILAN (2010) ====================

    Player int1;
    int1.name = "JULIO CESAR";
    int1.nationality = "Brazilian";
    int1.role = "Goalkeeper";
    int1.position = "GK";
    int1.age = 30;
    int1.shooting = 10;
    int1.passing = 50;
    int1.dribbling = 38;
    int1.pace = 40;
    int1.defending = 20;
    int1.physical = 60;
    int1.goalkeeping = 89;

    Player int2;
    int2.name = "LUCIO";
    int2.nationality = "Brazilian";
    int2.role = "Defender";
    int2.position = "CB";
    int2.age = 32;
    int2.shooting = 30;
    int2.passing = 62;
    int2.dribbling = 60;
    int2.pace = 68;
    int2.defending = 86;
    int2.physical = 80;
    int2.goalkeeping = 5;

    Player int3;
    int3.name = "WALTER SAMUEL";
    int3.nationality = "Argentine";
    int3.role = "Defender";
    int3.position = "CB";
    int3.age = 31;
    int3.shooting = 24;
    int3.passing = 54;
    int3.dribbling = 48;
    int3.pace = 56;
    int3.defending = 87;
    int3.physical = 82;
    int3.goalkeeping = 5;

    Player int4;
    int4.name = "MAICON";
    int4.nationality = "Brazilian";
    int4.role = "Defender";
    int4.position = "RB";
    int4.age = 28;
    int4.shooting = 68;
    int4.passing = 72;
    int4.dribbling = 80;
    int4.pace = 86;
    int4.defending = 80;
    int4.physical = 78;
    int4.goalkeeping = 5;

    Player int5;
    int5.name = "CRISTIAN CHIVU";
    int5.nationality = "Romanian";
    int5.role = "Defender";
    int5.position = "LB";
    int5.age = 29;
    int5.shooting = 32;
    int5.passing = 60;
    int5.dribbling = 58;
    int5.pace = 60;
    int5.defending = 78;
    int5.physical = 72;
    int5.goalkeeping = 5;

    Player int6;
    int6.name = "WESLEY SNEIJDER";
    int6.nationality = "Dutch";
    int6.role = "Midfielder";
    int6.position = "CAM";
    int6.age = 26;
    int6.shooting = 84;
    int6.passing = 90;
    int6.dribbling = 82;
    int6.pace = 72;
    int6.defending = 62;
    int6.physical = 72;
    int6.goalkeeping = 5;

    Player int7;
    int7.name = "JAVIER ZANETTI";
    int7.nationality = "Argentine";
    int7.role = "Midfielder";
    int7.position = "CM";
    int7.age = 36;
    int7.shooting = 52;
    int7.passing = 74;
    int7.dribbling = 72;
    int7.pace = 80;
    int7.defending = 78;
    int7.physical = 78;
    int7.goalkeeping = 5;

    Player int8;
    int8.name = "ESTEBAN CAMBIASSO";
    int8.nationality = "Argentine";
    int8.role = "Midfielder";
    int8.position = "CDM";
    int8.age = 29;
    int8.shooting = 56;
    int8.passing = 76;
    int8.dribbling = 66;
    int8.pace = 62;
    int8.defending = 82;
    int8.physical = 78;
    int8.goalkeeping = 5;

    Player int9;
    int9.name = "DEJAN STANKOVIC";
    int9.nationality = "Serbian";
    int9.role = "Midfielder";
    int9.position = "CM";
    int9.age = 31;
    int9.shooting = 66;
    int9.passing = 74;
    int9.dribbling = 70;
    int9.pace = 66;
    int9.defending = 68;
    int9.physical = 76;
    int9.goalkeeping = 5;

    Player int10;
    int10.name = "DIEGO MILITO";
    int10.nationality = "Argentine";
    int10.role = "Attacker";
    int10.position = "ST";
    int10.age = 30;
    int10.shooting = 88;
    int10.passing = 68;
    int10.dribbling = 72;
    int10.pace = 72;
    int10.defending = 34;
    int10.physical = 72;
    int10.goalkeeping = 5;

    Player int11;
    int11.name = "SAMUEL ETOO";
    int11.nationality = "Cameroonian";
    int11.role = "Attacker";
    int11.position = "CF";
    int11.age = 29;
    int11.shooting = 88;
    int11.passing = 70;
    int11.dribbling = 84;
    int11.pace = 90;
    int11.defending = 42;
    int11.physical = 80;
    int11.goalkeeping = 5;

    Team inter;
    inter.name = "INTER MILAN";
    inter.players.push_back(int1);
    inter.players.push_back(int2);
    inter.players.push_back(int3);
    inter.players.push_back(int4);
    inter.players.push_back(int5);
    inter.players.push_back(int6);
    inter.players.push_back(int7);
    inter.players.push_back(int8);
    inter.players.push_back(int9);
    inter.players.push_back(int10);
    inter.players.push_back(int11);

    // ==================== BAYERN MUNICH (2013) ====================

    Player bay1;
    bay1.name = "MANUEL NEUER";
    bay1.nationality = "German";
    bay1.role = "Goalkeeper";
    bay1.position = "GK";
    bay1.age = 27;
    bay1.shooting = 12;
    bay1.passing = 68;
    bay1.dribbling = 52;
    bay1.pace = 56;
    bay1.defending = 28;
    bay1.physical = 70;
    bay1.goalkeeping = 95;

    Player bay2;
    bay2.name = "PHILIPP LAHM";
    bay2.nationality = "German";
    bay2.role = "Defender";
    bay2.position = "RB";
    bay2.age = 29;
    bay2.shooting = 58;
    bay2.passing = 84;
    bay2.dribbling = 78;
    bay2.pace = 78;
    bay2.defending = 84;
    bay2.physical = 72;
    bay2.goalkeeping = 5;

    Player bay3;
    bay3.name = "JEROME BOATENG";
    bay3.nationality = "German";
    bay3.role = "Defender";
    bay3.position = "CB";
    bay3.age = 24;
    bay3.shooting = 28;
    bay3.passing = 62;
    bay3.dribbling = 58;
    bay3.pace = 68;
    bay3.defending = 88;
    bay3.physical = 80;
    bay3.goalkeeping = 5;

    Player bay4;
    bay4.name = "DANTE";
    bay4.nationality = "Brazilian";
    bay4.role = "Defender";
    bay4.position = "CB";
    bay4.age = 29;
    bay4.shooting = 24;
    bay4.passing = 58;
    bay4.dribbling = 52;
    bay4.pace = 60;
    bay4.defending = 84;
    bay4.physical = 78;
    bay4.goalkeeping = 5;

    Player bay5;
    bay5.name = "DAVID ALABA";
    bay5.nationality = "Austrian";
    bay5.role = "Defender";
    bay5.position = "LB";
    bay5.age = 20;
    bay5.shooting = 52;
    bay5.passing = 76;
    bay5.dribbling = 74;
    bay5.pace = 76;
    bay5.defending = 80;
    bay5.physical = 72;
    bay5.goalkeeping = 5;

    Player bay6;
    bay6.name = "BASTIAN SCHWEINSTEIGER";
    bay6.nationality = "German";
    bay6.role = "Midfielder";
    bay6.position = "CM";
    bay6.age = 28;
    bay6.shooting = 72;
    bay6.passing = 84;
    bay6.dribbling = 78;
    bay6.pace = 66;
    bay6.defending = 74;
    bay6.physical = 80;
    bay6.goalkeeping = 5;

    Player bay7;
    bay7.name = "JAVI MARTINEZ";
    bay7.nationality = "Spanish";
    bay7.role = "Midfielder";
    bay7.position = "CDM";
    bay7.age = 24;
    bay7.shooting = 52;
    bay7.passing = 74;
    bay7.dribbling = 64;
    bay7.pace = 58;
    bay7.defending = 84;
    bay7.physical = 82;
    bay7.goalkeeping = 5;

    Player bay8;
    bay8.name = "TONI KROOS";
    bay8.nationality = "German";
    bay8.role = "Midfielder";
    bay8.position = "CM";
    bay8.age = 23;
    bay8.shooting = 74;
    bay8.passing = 90;
    bay8.dribbling = 76;
    bay8.pace = 58;
    bay8.defending = 66;
    bay8.physical = 68;
    bay8.goalkeeping = 5;

    Player bay9;
    bay9.name = "FRANCK RIBERY";
    bay9.nationality = "French";
    bay9.role = "Attacker";
    bay9.position = "LW";
    bay9.age = 30;
    bay9.shooting = 82;
    bay9.passing = 80;
    bay9.dribbling = 92;
    bay9.pace = 84;
    bay9.defending = 40;
    bay9.physical = 70;
    bay9.goalkeeping = 5;

    Player bay10;
    bay10.name = "ARJEN ROBBEN";
    bay10.nationality = "Dutch";
    bay10.role = "Attacker";
    bay10.position = "RW";
    bay10.age = 29;
    bay10.shooting = 88;
    bay10.passing = 76;
    bay10.dribbling = 90;
    bay10.pace = 86;
    bay10.defending = 36;
    bay10.physical = 68;
    bay10.goalkeeping = 5;

    Player bay11;
    bay11.name = "THOMAS MULLER";
    bay11.nationality = "German";
    bay11.role = "Attacker";
    bay11.position = "CF";
    bay11.age = 23;
    bay11.shooting = 80;
    bay11.passing = 80;
    bay11.dribbling = 76;
    bay11.pace = 72;
    bay11.defending = 52;
    bay11.physical = 72;
    bay11.goalkeeping = 5;

    Team bay;
    bay.name = "BAYERN MUNICH";
    bay.players.push_back(bay1);
    bay.players.push_back(bay2);
    bay.players.push_back(bay3);
    bay.players.push_back(bay4);
    bay.players.push_back(bay5);
    bay.players.push_back(bay6);
    bay.players.push_back(bay7);
    bay.players.push_back(bay8);
    bay.players.push_back(bay9);
    bay.players.push_back(bay10);
    bay.players.push_back(bay11);

    // ==================== ARSENAL (2004) ====================

    Player ars1;
    ars1.name = "JENS LEHMANN";
    ars1.nationality = "German";
    ars1.role = "Goalkeeper";
    ars1.position = "GK";
    ars1.age = 34;
    ars1.shooting = 10;
    ars1.passing = 50;
    ars1.dribbling = 38;
    ars1.pace = 38;
    ars1.defending = 20;
    ars1.physical = 64;
    ars1.goalkeeping = 88;

    Player ars2;
    ars2.name = "SOL CAMPBELL";
    ars2.nationality = "English";
    ars2.role = "Defender";
    ars2.position = "CB";
    ars2.age = 29;
    ars2.shooting = 28;
    ars2.passing = 58;
    ars2.dribbling = 50;
    ars2.pace = 60;
    ars2.defending = 90;
    ars2.physical = 86;
    ars2.goalkeeping = 5;

    Player ars3;
    ars3.name = "ASHLEY COLE";
    ars3.nationality = "English";
    ars3.role = "Defender";
    ars3.position = "LB";
    ars3.age = 23;
    ars3.shooting = 48;
    ars3.passing = 68;
    ars3.dribbling = 72;
    ars3.pace = 84;
    ars3.defending = 80;
    ars3.physical = 74;
    ars3.goalkeeping = 5;

    Player ars4;
    ars4.name = "KOLO TOURE";
    ars4.nationality = "Ivorian";
    ars4.role = "Defender";
    ars4.position = "CB";
    ars4.age = 23;
    ars4.shooting = 26;
    ars4.passing = 56;
    ars4.dribbling = 54;
    ars4.pace = 72;
    ars4.defending = 83;
    ars4.physical = 82;
    ars4.goalkeeping = 5;

    Player ars5;
    ars5.name = "LAUREN";
    ars5.nationality = "Cameroonian";
    ars5.role = "Defender";
    ars5.position = "RB";
    ars5.age = 27;
    ars5.shooting = 44;
    ars5.passing = 62;
    ars5.dribbling = 58;
    ars5.pace = 66;
    ars5.defending = 76;
    ars5.physical = 72;
    ars5.goalkeeping = 5;

    Player ars6;
    ars6.name = "PATRICK VIEIRA";
    ars6.nationality = "French";
    ars6.role = "Midfielder";
    ars6.position = "CM";
    ars6.age = 27;
    ars6.shooting = 68;
    ars6.passing = 80;
    ars6.dribbling = 72;
    ars6.pace = 72;
    ars6.defending = 82;
    ars6.physical = 88;
    ars6.goalkeeping = 5;

    Player ars7;
    ars7.name = "ROBERT PIRES";
    ars7.nationality = "French";
    ars7.role = "Midfielder";
    ars7.position = "LM";
    ars7.age = 30;
    ars7.shooting = 78;
    ars7.passing = 80;
    ars7.dribbling = 84;
    ars7.pace = 72;
    ars7.defending = 48;
    ars7.physical = 66;
    ars7.goalkeeping = 5;

    Player ars8;
    ars8.name = "FREDDIE LJUNGBERG";
    ars8.nationality = "Swedish";
    ars8.role = "Midfielder";
    ars8.position = "RM";
    ars8.age = 27;
    ars8.shooting = 74;
    ars8.passing = 72;
    ars8.dribbling = 80;
    ars8.pace = 78;
    ars8.defending = 52;
    ars8.physical = 72;
    ars8.goalkeeping = 5;

    Player ars9;
    ars9.name = "GILBERTO SILVA";
    ars9.nationality = "Brazilian";
    ars9.role = "Midfielder";
    ars9.position = "CDM";
    ars9.age = 27;
    ars9.shooting = 50;
    ars9.passing = 70;
    ars9.dribbling = 60;
    ars9.pace = 58;
    ars9.defending = 80;
    ars9.physical = 78;
    ars9.goalkeeping = 5;

    Player ars10;
    ars10.name = "THIERRY HENRY";
    ars10.nationality = "French";
    ars10.role = "Attacker";
    ars10.position = "ST";
    ars10.age = 26;
    ars10.shooting = 92;
    ars10.passing = 82;
    ars10.dribbling = 94;
    ars10.pace = 96;
    ars10.defending = 38;
    ars10.physical = 76;
    ars10.goalkeeping = 5;

    Player ars11;
    ars11.name = "DENNIS BERGKAMP";
    ars11.nationality = "Dutch";
    ars11.role = "Attacker";
    ars11.position = "CF";
    ars11.age = 34;
    ars11.shooting = 86;
    ars11.passing = 88;
    ars11.dribbling = 86;
    ars11.pace = 58;
    ars11.defending = 38;
    ars11.physical = 64;
    ars11.goalkeeping = 5;

    Team ars;
    ars.name = "ARSENAL";
    ars.players.push_back(ars1);
    ars.players.push_back(ars2);
    ars.players.push_back(ars3);
    ars.players.push_back(ars4);
    ars.players.push_back(ars5);
    ars.players.push_back(ars6);
    ars.players.push_back(ars7);
    ars.players.push_back(ars8);
    ars.players.push_back(ars9);
    ars.players.push_back(ars10);
    ars.players.push_back(ars11);

    // ==================== ATLETICO MADRID (2016) ====================

    Player atl1;
    atl1.name = "JAN OBLAK";
    atl1.nationality = "Slovenian";
    atl1.role = "Goalkeeper";
    atl1.position = "GK";
    atl1.age = 23;
    atl1.shooting = 10;
    atl1.passing = 50;
    atl1.dribbling = 38;
    atl1.pace = 40;
    atl1.defending = 22;
    atl1.physical = 66;
    atl1.goalkeeping = 91;

    Player atl2;
    atl2.name = "DIEGO GODIN";
    atl2.nationality = "Uruguayan";
    atl2.role = "Defender";
    atl2.position = "CB";
    atl2.age = 30;
    atl2.shooting = 32;
    atl2.passing = 64;
    atl2.dribbling = 56;
    atl2.pace = 58;
    atl2.defending = 92;
    atl2.physical = 86;
    atl2.goalkeeping = 5;

    Player atl3;
    atl3.name = "JOSE GIMENEZ";
    atl3.nationality = "Uruguayan";
    atl3.role = "Defender";
    atl3.position = "CB";
    atl3.age = 21;
    atl3.shooting = 28;
    atl3.passing = 58;
    atl3.dribbling = 54;
    atl3.pace = 62;
    atl3.defending = 83;
    atl3.physical = 80;
    atl3.goalkeeping = 5;

    Player atl4;
    atl4.name = "JUANFRAN";
    atl4.nationality = "Spanish";
    atl4.role = "Defender";
    atl4.position = "RB";
    atl4.age = 31;
    atl4.shooting = 50;
    atl4.passing = 64;
    atl4.dribbling = 62;
    atl4.pace = 72;
    atl4.defending = 78;
    atl4.physical = 72;
    atl4.goalkeeping = 5;

    Player atl5;
    atl5.name = "FILIPE LUIS";
    atl5.nationality = "Brazilian";
    atl5.role = "Defender";
    atl5.position = "LB";
    atl5.age = 30;
    atl5.shooting = 54;
    atl5.passing = 72;
    atl5.dribbling = 70;
    atl5.pace = 76;
    atl5.defending = 80;
    atl5.physical = 72;
    atl5.goalkeeping = 5;

    Player atl6;
    atl6.name = "KOKE";
    atl6.nationality = "Spanish";
    atl6.role = "Midfielder";
    atl6.position = "CM";
    atl6.age = 24;
    atl6.shooting = 62;
    atl6.passing = 86;
    atl6.dribbling = 80;
    atl6.pace = 72;
    atl6.defending = 68;
    atl6.physical = 70;
    atl6.goalkeeping = 5;

    Player atl7;
    atl7.name = "SAUL NIGUEZ";
    atl7.nationality = "Spanish";
    atl7.role = "Midfielder";
    atl7.position = "CM";
    atl7.age = 21;
    atl7.shooting = 72;
    atl7.passing = 76;
    atl7.dribbling = 78;
    atl7.pace = 76;
    atl7.defending = 72;
    atl7.physical = 80;
    atl7.goalkeeping = 5;

    Player atl8;
    atl8.name = "GABI";
    atl8.nationality = "Spanish";
    atl8.role = "Midfielder";
    atl8.position = "CDM";
    atl8.age = 32;
    atl8.shooting = 52;
    atl8.passing = 74;
    atl8.dribbling = 64;
    atl8.pace = 62;
    atl8.defending = 78;
    atl8.physical = 76;
    atl8.goalkeeping = 5;

    Player atl9;
    atl9.name = "YANNICK CARRASCO";
    atl9.nationality = "Belgian";
    atl9.role = "Attacker";
    atl9.position = "LW";
    atl9.age = 22;
    atl9.shooting = 72;
    atl9.passing = 68;
    atl9.dribbling = 82;
    atl9.pace = 82;
    atl9.defending = 40;
    atl9.physical = 70;
    atl9.goalkeeping = 5;

    Player atl10;
    atl10.name = "ANTOINE GRIEZMANN";
    atl10.nationality = "French";
    atl10.role = "Attacker";
    atl10.position = "ST";
    atl10.age = 25;
    atl10.shooting = 88;
    atl10.passing = 82;
    atl10.dribbling = 86;
    atl10.pace = 82;
    atl10.defending = 50;
    atl10.physical = 72;
    atl10.goalkeeping = 5;

    Player atl11;
    atl11.name = "FERNANDO TORRES";
    atl11.nationality = "Spanish";
    atl11.role = "Attacker";
    atl11.position = "CF";
    atl11.age = 32;
    atl11.shooting = 80;
    atl11.passing = 62;
    atl11.dribbling = 70;
    atl11.pace = 76;
    atl11.defending = 32;
    atl11.physical = 72;
    atl11.goalkeeping = 5;

    Team atl;
    atl.name = "ATLETICO MADRID";
    atl.players.push_back(atl1);
    atl.players.push_back(atl2);
    atl.players.push_back(atl3);
    atl.players.push_back(atl4);
    atl.players.push_back(atl5);
    atl.players.push_back(atl6);
    atl.players.push_back(atl7);
    atl.players.push_back(atl8);
    atl.players.push_back(atl9);
    atl.players.push_back(atl10);
    atl.players.push_back(atl11);

    // ==================== PSG (2020) ====================

    Player psg1;
    psg1.name = "KEYLOR NAVAS";
    psg1.nationality = "Costa Rican";
    psg1.role = "Goalkeeper";
    psg1.position = "GK";
    psg1.age = 33;
    psg1.shooting = 10;
    psg1.passing = 52;
    psg1.dribbling = 42;
    psg1.pace = 44;
    psg1.defending = 22;
    psg1.physical = 60;
    psg1.goalkeeping = 88;

    Player psg2;
    psg2.name = "THIAGO SILVA";
    psg2.nationality = "Brazilian";
    psg2.role = "Defender";
    psg2.position = "CB";
    psg2.age = 35;
    psg2.shooting = 28;
    psg2.passing = 68;
    psg2.dribbling = 58;
    psg2.pace = 56;
    psg2.defending = 88;
    psg2.physical = 78;
    psg2.goalkeeping = 5;

    Player psg3;
    psg3.name = "MARQUINHOS";
    psg3.nationality = "Brazilian";
    psg3.role = "Defender";
    psg3.position = "CB";
    psg3.age = 26;
    psg3.shooting = 32;
    psg3.passing = 72;
    psg3.dribbling = 64;
    psg3.pace = 62;
    psg3.defending = 88;
    psg3.physical = 78;
    psg3.goalkeeping = 5;

    Player psg4;
    psg4.name = "JUAN BERNAT";
    psg4.nationality = "Spanish";
    psg4.role = "Defender";
    psg4.position = "LB";
    psg4.age = 27;
    psg4.shooting = 46;
    psg4.passing = 68;
    psg4.dribbling = 68;
    psg4.pace = 74;
    psg4.defending = 74;
    psg4.physical = 68;
    psg4.goalkeeping = 5;

    Player psg5;
    psg5.name = "THOMAS MEUNIER";
    psg5.nationality = "Belgian";
    psg5.role = "Defender";
    psg5.position = "RB";
    psg5.age = 28;
    psg5.shooting = 56;
    psg5.passing = 68;
    psg5.dribbling = 66;
    psg5.pace = 76;
    psg5.defending = 72;
    psg5.physical = 74;
    psg5.goalkeeping = 5;

    Player psg6;
    psg6.name = "MARCO VERRATTI";
    psg6.nationality = "Italian";
    psg6.role = "Midfielder";
    psg6.position = "CM";
    psg6.age = 27;
    psg6.shooting = 62;
    psg6.passing = 90;
    psg6.dribbling = 84;
    psg6.pace = 68;
    psg6.defending = 70;
    psg6.physical = 68;
    psg6.goalkeeping = 5;

    Player psg7;
    psg7.name = "LEANDRO PAREDES";
    psg7.nationality = "Argentine";
    psg7.role = "Midfielder";
    psg7.position = "CDM";
    psg7.age = 25;
    psg7.shooting = 56;
    psg7.passing = 80;
    psg7.dribbling = 68;
    psg7.pace = 56;
    psg7.defending = 74;
    psg7.physical = 72;
    psg7.goalkeeping = 5;

    Player psg8;
    psg8.name = "ANGEL DI MARIA";
    psg8.nationality = "Argentine";
    psg8.role = "Attacker";
    psg8.position = "RW";
    psg8.age = 32;
    psg8.shooting = 82;
    psg8.passing = 84;
    psg8.dribbling = 88;
    psg8.pace = 84;
    psg8.defending = 42;
    psg8.physical = 68;
    psg8.goalkeeping = 5;

    Player psg9;
    psg9.name = "ANDER HERRERA";
    psg9.nationality = "Spanish";
    psg9.role = "Midfielder";
    psg9.position = "CM";
    psg9.age = 30;
    psg9.shooting = 62;
    psg9.passing = 76;
    psg9.dribbling = 70;
    psg9.pace = 66;
    psg9.defending = 72;
    psg9.physical = 76;
    psg9.goalkeeping = 5;

    Player psg10;
    psg10.name = "NEYMAR JR";
    psg10.nationality = "Brazilian";
    psg10.role = "Attacker";
    psg10.position = "LW";
    psg10.age = 28;
    psg10.shooting = 88;
    psg10.passing = 86;
    psg10.dribbling = 96;
    psg10.pace = 82;
    psg10.defending = 38;
    psg10.physical = 66;
    psg10.goalkeeping = 5;

    Player psg11;
    psg11.name = "KYLIAN MBAPPE";
    psg11.nationality = "French";
    psg11.role = "Attacker";
    psg11.position = "ST";
    psg11.age = 21;
    psg11.shooting = 90;
    psg11.passing = 80;
    psg11.dribbling = 92;
    psg11.pace = 97;
    psg11.defending = 38;
    psg11.physical = 78;
    psg11.goalkeeping = 5;

    Team psg;
    psg.name = "PSG";
    psg.players.push_back(psg1);
    psg.players.push_back(psg2);
    psg.players.push_back(psg3);
    psg.players.push_back(psg4);
    psg.players.push_back(psg5);
    psg.players.push_back(psg6);
    psg.players.push_back(psg7);
    psg.players.push_back(psg8);
    psg.players.push_back(psg9);
    psg.players.push_back(psg10);
    psg.players.push_back(psg11);

    // ==================== DORTMUND (2013) ====================

    Player bvb1;
    bvb1.name = "ROMAN WEIDENFELLER";
    bvb1.nationality = "German";
    bvb1.role = "Goalkeeper";
    bvb1.position = "GK";
    bvb1.age = 32;
    bvb1.shooting = 10;
    bvb1.passing = 48;
    bvb1.dribbling = 38;
    bvb1.pace = 40;
    bvb1.defending = 20;
    bvb1.physical = 60;
    bvb1.goalkeeping = 86;

    Player bvb2;
    bvb2.name = "MATS HUMMELS";
    bvb2.nationality = "German";
    bvb2.role = "Defender";
    bvb2.position = "CB";
    bvb2.age = 24;
    bvb2.shooting = 30;
    bvb2.passing = 70;
    bvb2.dribbling = 58;
    bvb2.pace = 60;
    bvb2.defending = 89;
    bvb2.physical = 80;
    bvb2.goalkeeping = 5;

    Player bvb3;
    bvb3.name = "NEVEN SUBOTIC";
    bvb3.nationality = "Serbian";
    bvb3.role = "Defender";
    bvb3.position = "CB";
    bvb3.age = 24;
    bvb3.shooting = 24;
    bvb3.passing = 56;
    bvb3.dribbling = 52;
    bvb3.pace = 64;
    bvb3.defending = 84;
    bvb3.physical = 78;
    bvb3.goalkeeping = 5;

    Player bvb4;
    bvb4.name = "LUKASZ PISZCZEK";
    bvb4.nationality = "Polish";
    bvb4.role = "Defender";
    bvb4.position = "RB";
    bvb4.age = 27;
    bvb4.shooting = 56;
    bvb4.passing = 68;
    bvb4.dribbling = 68;
    bvb4.pace = 80;
    bvb4.defending = 76;
    bvb4.physical = 74;
    bvb4.goalkeeping = 5;

    Player bvb5;
    bvb5.name = "MARCEL SCHMELZER";
    bvb5.nationality = "German";
    bvb5.role = "Defender";
    bvb5.position = "LB";
    bvb5.age = 25;
    bvb5.shooting = 46;
    bvb5.passing = 64;
    bvb5.dribbling = 64;
    bvb5.pace = 76;
    bvb5.defending = 74;
    bvb5.physical = 70;
    bvb5.goalkeeping = 5;

    Player bvb6;
    bvb6.name = "ILKAY GUNDOGAN";
    bvb6.nationality = "German";
    bvb6.role = "Midfielder";
    bvb6.position = "CDM";
    bvb6.age = 22;
    bvb6.shooting = 60;
    bvb6.passing = 82;
    bvb6.dribbling = 74;
    bvb6.pace = 62;
    bvb6.defending = 70;
    bvb6.physical = 70;
    bvb6.goalkeeping = 5;

    Player bvb7;
    bvb7.name = "SVEN BENDER";
    bvb7.nationality = "German";
    bvb7.role = "Midfielder";
    bvb7.position = "CDM";
    bvb7.age = 24;
    bvb7.shooting = 48;
    bvb7.passing = 70;
    bvb7.dribbling = 62;
    bvb7.pace = 66;
    bvb7.defending = 78;
    bvb7.physical = 76;
    bvb7.goalkeeping = 5;

    Player bvb8;
    bvb8.name = "MARCO REUS";
    bvb8.nationality = "German";
    bvb8.role = "Midfielder";
    bvb8.position = "CAM";
    bvb8.age = 24;
    bvb8.shooting = 84;
    bvb8.passing = 82;
    bvb8.dribbling = 88;
    bvb8.pace = 88;
    bvb8.defending = 46;
    bvb8.physical = 70;
    bvb8.goalkeeping = 5;

    Player bvb9;
    bvb9.name = "JAKUB BLASZCZYKOWSKI";
    bvb9.nationality = "Polish";
    bvb9.role = "Midfielder";
    bvb9.position = "RM";
    bvb9.age = 27;
    bvb9.shooting = 74;
    bvb9.passing = 70;
    bvb9.dribbling = 76;
    bvb9.pace = 80;
    bvb9.defending = 44;
    bvb9.physical = 68;
    bvb9.goalkeeping = 5;

    Player bvb10;
    bvb10.name = "ROBERT LEWANDOWSKI";
    bvb10.nationality = "Polish";
    bvb10.role = "Attacker";
    bvb10.position = "ST";
    bvb10.age = 24;
    bvb10.shooting = 90;
    bvb10.passing = 68;
    bvb10.dribbling = 72;
    bvb10.pace = 76;
    bvb10.defending = 38;
    bvb10.physical = 80;
    bvb10.goalkeeping = 5;

    Player bvb11;
    bvb11.name = "MARIO GOTZE";
    bvb11.nationality = "German";
    bvb11.role = "Attacker";
    bvb11.position = "CF";
    bvb11.age = 21;
    bvb11.shooting = 78;
    bvb11.passing = 82;
    bvb11.dribbling = 88;
    bvb11.pace = 76;
    bvb11.defending = 46;
    bvb11.physical = 66;
    bvb11.goalkeeping = 5;

    Team bvb;
    bvb.name = "DORTMUND";
    bvb.players.push_back(bvb1);
    bvb.players.push_back(bvb2);
    bvb.players.push_back(bvb3);
    bvb.players.push_back(bvb4);
    bvb.players.push_back(bvb5);
    bvb.players.push_back(bvb6);
    bvb.players.push_back(bvb7);
    bvb.players.push_back(bvb8);
    bvb.players.push_back(bvb9);
    bvb.players.push_back(bvb10);
    bvb.players.push_back(bvb11);

    // ==================== LEVERKUSEN (2024) ====================

    Player lev1;
    lev1.name = "LUKAS HRADECKY";
    lev1.nationality = "Finnish";
    lev1.role = "Goalkeeper";
    lev1.position = "GK";
    lev1.age = 34;
    lev1.shooting = 10;
    lev1.passing = 52;
    lev1.dribbling = 38;
    lev1.pace = 38;
    lev1.defending = 20;
    lev1.physical = 62;
    lev1.goalkeeping = 86;

    Player lev2;
    lev2.name = "JONATHAN TAH";
    lev2.nationality = "German";
    lev2.role = "Defender";
    lev2.position = "CB";
    lev2.age = 28;
    lev2.shooting = 28;
    lev2.passing = 62;
    lev2.dribbling = 54;
    lev2.pace = 62;
    lev2.defending = 86;
    lev2.physical = 80;
    lev2.goalkeeping = 5;

    Player lev3;
    lev3.name = "EDMOND TAPSOBA";
    lev3.nationality = "Burkinabe";
    lev3.role = "Defender";
    lev3.position = "CB";
    lev3.age = 24;
    lev3.shooting = 24;
    lev3.passing = 58;
    lev3.dribbling = 58;
    lev3.pace = 72;
    lev3.defending = 83;
    lev3.physical = 80;
    lev3.goalkeeping = 5;

    Player lev4;
    lev4.name = "JEREMIE FRIMPONG";
    lev4.nationality = "Dutch";
    lev4.role = "Defender";
    lev4.position = "RWB";
    lev4.age = 23;
    lev4.shooting = 64;
    lev4.passing = 70;
    lev4.dribbling = 78;
    lev4.pace = 94;
    lev4.defending = 66;
    lev4.physical = 72;
    lev4.goalkeeping = 5;

    Player lev5;
    lev5.name = "ALEJANDRO GRIMALDO";
    lev5.nationality = "Spanish";
    lev5.role = "Defender";
    lev5.position = "LWB";
    lev5.age = 28;
    lev5.shooting = 66;
    lev5.passing = 76;
    lev5.dribbling = 78;
    lev5.pace = 84;
    lev5.defending = 72;
    lev5.physical = 70;
    lev5.goalkeeping = 5;

    Player lev6;
    lev6.name = "GRANIT XHAKA";
    lev6.nationality = "Swiss";
    lev6.role = "Midfielder";
    lev6.position = "CDM";
    lev6.age = 31;
    lev6.shooting = 68;
    lev6.passing = 82;
    lev6.dribbling = 70;
    lev6.pace = 60;
    lev6.defending = 78;
    lev6.physical = 78;
    lev6.goalkeeping = 5;

    Player lev7;
    lev7.name = "EXEQUIEL PALACIOS";
    lev7.nationality = "Argentine";
    lev7.role = "Midfielder";
    lev7.position = "CM";
    lev7.age = 25;
    lev7.shooting = 60;
    lev7.passing = 76;
    lev7.dribbling = 72;
    lev7.pace = 66;
    lev7.defending = 72;
    lev7.physical = 74;
    lev7.goalkeeping = 5;

    Player lev8;
    lev8.name = "FLORIAN WIRTZ";
    lev8.nationality = "German";
    lev8.role = "Midfielder";
    lev8.position = "CAM";
    lev8.age = 20;
    lev8.shooting = 82;
    lev8.passing = 86;
    lev8.dribbling = 90;
    lev8.pace = 78;
    lev8.defending = 50;
    lev8.physical = 66;
    lev8.goalkeeping = 5;

    Player lev9;
    lev9.name = "JONAS HOFMANN";
    lev9.nationality = "German";
    lev9.role = "Attacker";
    lev9.position = "RW";
    lev9.age = 31;
    lev9.shooting = 74;
    lev9.passing = 72;
    lev9.dribbling = 76;
    lev9.pace = 76;
    lev9.defending = 54;
    lev9.physical = 70;
    lev9.goalkeeping = 5;

    Player lev10;
    lev10.name = "VICTOR BONIFACE";
    lev10.nationality = "Nigerian";
    lev10.role = "Attacker";
    lev10.position = "ST";
    lev10.age = 23;
    lev10.shooting = 84;
    lev10.passing = 64;
    lev10.dribbling = 76;
    lev10.pace = 84;
    lev10.defending = 38;
    lev10.physical = 80;
    lev10.goalkeeping = 5;

    Player lev11;
    lev11.name = "PATRIK SCHICK";
    lev11.nationality = "Czech";
    lev11.role = "Attacker";
    lev11.position = "ST";
    lev11.age = 28;
    lev11.shooting = 84;
    lev11.passing = 62;
    lev11.dribbling = 68;
    lev11.pace = 68;
    lev11.defending = 34;
    lev11.physical = 76;
    lev11.goalkeeping = 5;

    Team lev;
    lev.name = "LEVERKUSEN";
    lev.players.push_back(lev1);
    lev.players.push_back(lev2);
    lev.players.push_back(lev3);
    lev.players.push_back(lev4);
    lev.players.push_back(lev5);
    lev.players.push_back(lev6);
    lev.players.push_back(lev7);
    lev.players.push_back(lev8);
    lev.players.push_back(lev9);
    lev.players.push_back(lev10);
    lev.players.push_back(lev11);

    // ==================== LYON (2006) ====================

    Player lyo1;
    lyo1.name = "GREGORY COUPET";
    lyo1.nationality = "French";
    lyo1.role = "Goalkeeper";
    lyo1.position = "GK";
    lyo1.age = 33;
    lyo1.shooting = 10;
    lyo1.passing = 50;
    lyo1.dribbling = 38;
    lyo1.pace = 40;
    lyo1.defending = 20;
    lyo1.physical = 60;
    lyo1.goalkeeping = 87;

    Player lyo2;
    lyo2.name = "CRIS";
    lyo2.nationality = "Brazilian";
    lyo2.role = "Defender";
    lyo2.position = "CB";
    lyo2.age = 29;
    lyo2.shooting = 26;
    lyo2.passing = 58;
    lyo2.dribbling = 52;
    lyo2.pace = 58;
    lyo2.defending = 86;
    lyo2.physical = 82;
    lyo2.goalkeeping = 5;

    Player lyo3;
    lyo3.name = "ERIC ABIDAL";
    lyo3.nationality = "French";
    lyo3.role = "Defender";
    lyo3.position = "LB";
    lyo3.age = 26;
    lyo3.shooting = 38;
    lyo3.passing = 64;
    lyo3.dribbling = 68;
    lyo3.pace = 78;
    lyo3.defending = 80;
    lyo3.physical = 72;
    lyo3.goalkeeping = 5;

    Player lyo4;
    lyo4.name = "ANTHONY REVEILLERE";
    lyo4.nationality = "French";
    lyo4.role = "Defender";
    lyo4.position = "RB";
    lyo4.age = 27;
    lyo4.shooting = 46;
    lyo4.passing = 62;
    lyo4.dribbling = 60;
    lyo4.pace = 72;
    lyo4.defending = 76;
    lyo4.physical = 72;
    lyo4.goalkeeping = 5;

    Player lyo5;
    lyo5.name = "PATRICK MULLER";
    lyo5.nationality = "Swiss";
    lyo5.role = "Defender";
    lyo5.position = "CB";
    lyo5.age = 29;
    lyo5.shooting = 22;
    lyo5.passing = 54;
    lyo5.dribbling = 48;
    lyo5.pace = 54;
    lyo5.defending = 82;
    lyo5.physical = 76;
    lyo5.goalkeeping = 5;

    Player lyo6;
    lyo6.name = "JUNINHO PERNAMBUCANO";
    lyo6.nationality = "Brazilian";
    lyo6.role = "Midfielder";
    lyo6.position = "CM";
    lyo6.age = 31;
    lyo6.shooting = 88;
    lyo6.passing = 84;
    lyo6.dribbling = 80;
    lyo6.pace = 62;
    lyo6.defending = 56;
    lyo6.physical = 70;
    lyo6.goalkeeping = 5;

    Player lyo7;
    lyo7.name = "MICHAEL ESSIEN";
    lyo7.nationality = "Ghanaian";
    lyo7.role = "Midfielder";
    lyo7.position = "CM";
    lyo7.age = 23;
    lyo7.shooting = 68;
    lyo7.passing = 72;
    lyo7.dribbling = 72;
    lyo7.pace = 80;
    lyo7.defending = 76;
    lyo7.physical = 88;
    lyo7.goalkeeping = 5;

    Player lyo8;
    lyo8.name = "TIAGO";
    lyo8.nationality = "Portuguese";
    lyo8.role = "Midfielder";
    lyo8.position = "CM";
    lyo8.age = 24;
    lyo8.shooting = 62;
    lyo8.passing = 78;
    lyo8.dribbling = 68;
    lyo8.pace = 66;
    lyo8.defending = 72;
    lyo8.physical = 76;
    lyo8.goalkeeping = 5;

    Player lyo9;
    lyo9.name = "FLORENT MALOUDA";
    lyo9.nationality = "French";
    lyo9.role = "Midfielder";
    lyo9.position = "LM";
    lyo9.age = 26;
    lyo9.shooting = 70;
    lyo9.passing = 72;
    lyo9.dribbling = 80;
    lyo9.pace = 82;
    lyo9.defending = 46;
    lyo9.physical = 70;
    lyo9.goalkeeping = 5;

    Player lyo10;
    lyo10.name = "KARIM BENZEMA";
    lyo10.nationality = "French";
    lyo10.role = "Attacker";
    lyo10.position = "ST";
    lyo10.age = 18;
    lyo10.shooting = 80;
    lyo10.passing = 68;
    lyo10.dribbling = 78;
    lyo10.pace = 78;
    lyo10.defending = 36;
    lyo10.physical = 68;
    lyo10.goalkeeping = 5;

    Player lyo11;
    lyo11.name = "SYLVAIN WILTORD";
    lyo11.nationality = "French";
    lyo11.role = "Attacker";
    lyo11.position = "LW";
    lyo11.age = 31;
    lyo11.shooting = 76;
    lyo11.passing = 68;
    lyo11.dribbling = 76;
    lyo11.pace = 80;
    lyo11.defending = 38;
    lyo11.physical = 68;
    lyo11.goalkeeping = 5;

    Team lyo;
    lyo.name = "LYON";
    lyo.players.push_back(lyo1);
    lyo.players.push_back(lyo2);
    lyo.players.push_back(lyo3);
    lyo.players.push_back(lyo4);
    lyo.players.push_back(lyo5);
    lyo.players.push_back(lyo6);
    lyo.players.push_back(lyo7);
    lyo.players.push_back(lyo8);
    lyo.players.push_back(lyo9);
    lyo.players.push_back(lyo10);
    lyo.players.push_back(lyo11);

    // ==================== PUSH ALL TEAMS ====================

    quickMatchTeams.push_back(bar);
    quickMatchTeams.push_back(rma);
    quickMatchTeams.push_back(mnu);
    quickMatchTeams.push_back(che);
    quickMatchTeams.push_back(liv);
    quickMatchTeams.push_back(mci);
    quickMatchTeams.push_back(mil);
    quickMatchTeams.push_back(juv);
    quickMatchTeams.push_back(inter);
    quickMatchTeams.push_back(bay);
    quickMatchTeams.push_back(ars);
    quickMatchTeams.push_back(atl);
    quickMatchTeams.push_back(psg);
    quickMatchTeams.push_back(bvb);
    quickMatchTeams.push_back(lev);
    quickMatchTeams.push_back(lyo);

    return quickMatchTeams;
}